pipeline {
    agent any

    tools {
        maven 'mvn'
    }

    environment {
        DOCKER_TOKEN = credentials('docker-token')
        SONARQUBE = 'sonarqube'
        SONAR_TOKEN = credentials('sonar-token')
        GITHUB_TOKEN = credentials('github-credentials')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: GITHUB_TOKEN, url: 'https://github.com/YassineOularbi/FILL-ROUGE-TAILORING-ONLINE.git'
            }
        }

        stage('Build and Test') {
            steps {
                bat 'mvn clean install'
                bat 'mvn test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv(SONARQUBE) {
                    bat "mvn sonar:sonar -Dsonar.token=${SONAR_TOKEN}"
                }
            }
        }

        stage('Quality Gate Check') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}