spring:
  application:
    name: store_management_service
  datasource:
    url: jdbc:mysql://localhost:3306/tailoring_store_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
    url: jdbc:mysql://localhost:3306/tailoring_store_db?createDatabaseIfNotExist=true
    user: root
    password: 1234
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/