spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/tailoring-online/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: user-management-app
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/tailoring-online
  application:
    name: store-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/tailoring_store_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
    url: jdbc:mysql://localhost:3306/tailoring_store_db?createDatabaseIfNotExist=true
    user: root
    password: 1234

server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/