spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/tailoring_user_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
