spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/tailoring_user_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
    url: jdbc:mysql://localhost:3306/tailoring_user_db?createDatabaseIfNotExist=true
    user: root
    password: 1234
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/tailoring-online/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: user-management-app
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/tailoring-online

server:
  port: 8081

openapi:
  service:
    title: USER-MANAGEMENT-SERVICE doc
    version: 1.0.0
    url: http://localhost:9191

springdoc:
  api-docs:
    path: /USER-MANAGEMENT-SERVICE/v3/api-docs
  swagger-ui:
    path: /USER-MANAGEMENT-SERVICE/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

keycloak:
  realm: tailoring-online
  auth-server-url: http://localhost:8080
  resource: user-management-app
  public-client: true
  use-resource-role-mappings: true
  username: admin-realm
  password: 1234
