spring:
  application:
    name: localization-shipping-service
  datasource:
    url: jdbc:mysql://localhost:3306/tailoring_localization_shipping_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    enabled: true
    url: jdbc:mysql://localhost:3306/tailoring_localization_shipping_db?createDatabaseIfNotExist=true
    user: root
    password: 1234

server:
  port: 8082

openapi:
  service:
    title: LOCALIZATION-SHIPPING-SERVICE doc
    version: 1.0.0
    url: http://localhost:9191

springdoc:
  api-docs:
    path: /LOCALIZATION-SHIPPING-SERVICE/v3/api-docs
  swagger-ui:
    path: /LOCALIZATION-SHIPPING-SERVICE/swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true