server:
  port: 9191

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /${path}/v3/api-docs

        - id: USER-MANAGEMENT-SERVICE
          uri: lb://user-management-service
          predicates:
            - Path=/USER-MANAGEMENT-SERVICE/** , /USER-MANAGEMENT-SERVICE/v3/api-docs
          filters:
            - RewritePath=/USER-MANAGEMENT-SERVICE/(?<path>.*), /${path}

        - id: LOCALIZATION-SHIPPING-SERVICE
          uri: lb://LOCALIZATION-SHIPPING-SERVICE
          predicates:
            - Path=/LOCALIZATION-SHIPPING-SERVICE/** , /LOCALIZATION-SHIPPING-SERVICE/v3/api-docs
          filters:
            - RewritePath=/LOCALIZATION-SHIPPING-SERVICE/(?<path>.*), /${path}

springdoc:
  enable-native-support: true
  api-docs:
    groups:
      enabled: true
    enabled: true
  group-configs:
    - group: USER-MANAGEMENT-SERVICE
      paths-to-match:
        - /USER-MANAGEMENT-SERVICE/**
      display-name: User Management Service
    - group: LOCALIZATION-SHIPPING-SERVICE
      paths-to-match:
        - /LOCALIZATION-SHIPPING-SERVICE/**
      display-name: Localization Shipping Service

  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    urls:
      - url: /USER-MANAGEMENT-SERVICE/v3/api-docs
        name: USER-MANAGEMENT-SERVICE
      - url: /LOCALIZATION-SHIPPING-SERVICE/v3/api-docs
        name: LOCALIZATION-SHIPPING-SERVICE
